# Generated by Django 3.0.7 on 2020-07-07 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='oficoda',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Oficoda'),
            preserve_default=False,
        ),
    ]
