# Generated by Django 3.0.7 on 2020-07-07 16:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bodega_oficoda'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bodega',
            name='unidad',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bodega',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
