# Generated by Django 3.0.7 on 2020-07-07 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200707_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodega',
            old_name='details',
            new_name='extra',
        ),
        migrations.AddField(
            model_name='distribucion',
            name='repartido',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='distribucion',
            name='sobrante',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='oficoda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='api.Oficoda'),
        ),
        migrations.AlterField(
            model_name='distribucion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='distribucion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='api.Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='notas',
            field=models.TextField(blank=True),
        ),
    ]
