# Generated by Django 3.0.7 on 2020-07-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200714_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucion',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='distribucion',
            name='repartido',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='distribucion',
            name='sobrante',
            field=models.PositiveIntegerField(),
        ),
    ]
